### ISSUE TITLE
weird problem even if rem'd

### ISSUE THREAD

**Issue by theenemy-thd** [GeorgRottensteiner/C64Studio#39]
I have a problem when adjusting text via the "*=$" command, it seems to then cause an issue here with the !binary command as it throws up an error and doesn't compile properly.

this is even if rem'd out.
delete after first rem'd out !text code and all ok... very strange

version 6.7 by the way

*edit = i can send files if needed

oh and thanks
Alex
![c64studiov67 issue](https://user-images.githubusercontent.com/78659007/115151848-97dec700-a066-11eb-82e9-26014d4dd439.png)

**Comment by GeorgRottensteiner** [comment]
Ah, nice catch :)

That's my dumb assembler type autodetect failing: It sees "ORG " in the file, and thus believes the assembler is DASM. Will be fixed ASAP!

**Comment by GeorgRottensteiner** [comment]
Fixed with commit 29fd1710

**Comment by GeorgRottensteiner** [comment]
Uploaded the fixed version to the usual link: https://www.georg-rottensteiner.de/files/C64StudioRelease.zip

**Comment by theenemy-thd** [comment]
> Uploaded the fixed version to the usual link: https://www.georg-rottensteiner.de/files/C64StudioRelease.zip

only just tried this and still having the same problem :(

errors with unused label !text and !binary

**Comment by GeorgRottensteiner** [comment]
Ah, my assembler type "detection" is not very smart. It found "org" inside the string literal and deemed it a DASM or PDS pseudo opcode.
Fixed with commit #c356eca7
